### ISSUE TITLE
QRCode - Data too big for requested version

### ISSUE THREAD

**Issue by froque** [premium-minds/billy#429]
```
Exception in thread "main" com.premiumminds.billy.gin.services.exceptions.ExportServiceException: com.premiumminds.billy.gin.services.exceptions.ExportServiceException: Error generating qrCode
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.ExportServiceImpl.exportToFile(ExportServiceImpl.java:88)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.ExportServiceImpl.exportToStream(ExportServiceImpl.java:64)
	at com.premiumminds.billy.portugal@8.0.1/com.premiumminds.billy.portugal.util.Invoices.pdfExport(Invoices.java:95)
	at DummyApp/dummyApp.app.PortugalDemoApp.exportInvoicePDF(PortugalDemoApp.java:386)
	at DummyApp/dummyApp.app.PortugalDemoApp.run(PortugalDemoApp.java:96)
	at DummyApp/dummyApp.app.App.main(App.java:32)
Caused by: com.premiumminds.billy.gin.services.exceptions.ExportServiceException: Error generating qrCode
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.pdf.FOPPDFTransformer.transformToStream(FOPPDFTransformer.java:150)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.pdf.AbstractFOPPDFTransformer.transform(AbstractFOPPDFTransformer.java:133)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.pdf.AbstractFOPPDFTransformer.transform(AbstractFOPPDFTransformer.java:42)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.ExportServiceImpl.doExport(ExportServiceImpl.java:139)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.ExportServiceImpl.exportWithTransformer(ExportServiceImpl.java:114)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.ExportServiceImpl.exportToFile(ExportServiceImpl.java:85)
	... 5 more
Caused by: com.google.zxing.WriterException: Data too big for requested version
	at com.google.zxing.qrcode.encoder.Encoder.encode(Encoder.java:144)
	at com.google.zxing.qrcode.QRCodeWriter.encode(QRCodeWriter.java:78)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.pdf.FOPPDFTransformer.createQR(FOPPDFTransformer.java:182)
	at com.premiumminds.billy.gin@8.0.1/com.premiumminds.billy.gin.services.impl.pdf.FOPPDFTransformer.transformToStream(FOPPDFTransformer.java:127)
	... 10 more
```

Version 9 is the minimum version required by Portuguese authorities. 

> A elaboração do código de barras bidimensional (código QR) deve obedecer às
seguintes especificações:
a) Taxa de Recuperação de Erro (ECC): “M”;
b) Tipo: Byte;
c) Pontos por módulo (Size): 2;
d) Versão: v=9 (valor mínimo);
e) Dimensões de imagem: mínimo 30x30 milímetros;
f)
Margem de Segurança (Margin): 0,25 cm.

https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/Faturacao/Paginas/Codigo_QR.aspx
https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/Novas_regras_faturacao/Documents/Especificacoes_Tecnicas_Codigo_QR.pdf

For version 9 the maximum data is 262 bytes for aphanumeric and ECC "M". 
https://www.qrcode.com/en/about/version.html

But the maximum data is about 735 characters corresponding to version 18 (816 characters). 

Ideas:
 * Replace hardcoded "9" with "18"
 * Dynamic calculate version from data length
 * Replace qrcode zxing library with alternative library https://github.com/nayuki/QR-Code-generator

**Comment by froque** [comment]
> But the maximum data is about 735 characters corresponding to version 18 (816 characters).

This is for alphanumeric characters. 

The alphanumeric characters for QRCode are 
> alphanumeric data (digits 0 - 9; upper case letters A - Z; nine other characters: space, $ % * + - . / : );
https://www.onbarcode.com/qr_code/
https://www.thonky.com/qr-code-tutorial/alphanumeric-table

lower case and ';' are not included. lowercase can be found in the Q _Hash_ field (example: Q:kLp0)
';' can be found in S field
> Na composição do campo com o código “S”, sempre que necessário, os
elementos que o compõem serão concatenados com «;» (ponto e virgula) sem
espaços;

So binary mode should be used, where version 9 has a maximum of 180 bytes and Version 22 has a maximum of 779 bytes.
